name: "Build All ports"

on: [push]
env:
  CARGO_TERM_COLOR: always

jobs:
  build-x86:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Update rustup
        run: rustup update && rustup default 1.88.0  && rustup target add x86_64-unknown-none && rustup +nightly component add rust-src
      - name: Install rust toolchain
        run: ./install_rust.sh
      - name: Build
        run: ./build_all.sh x86_64
      - name: Upload out/
        uses: actions/upload-artifact@v4.6.0
        with:
          name: out-x86_64
          path: out/
  build-aarch64:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Update rustup
        run: rustup update && rustup default 1.88.0 && rustup target add aarch64-unknown-none && rustup +nightly component add rust-src
      - name: Install rust toolchain
        run: ./install_rust.sh
      - name: Build
        run: ./build_all.sh aarch64
      - name: Upload out/
        uses: actions/upload-artifact@v4.6.0
        with:
          name: out-aarch64
          path: out/
  release:
    needs: [build-x86, build-aarch64]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download x86_64 out/
        uses: actions/download-artifact@v4
        with:
          name: out-x86_64
          path: out-x86_64/
      - name: Download aarch64 out/
        uses: actions/download-artifact@v4
        with:
          name: out-aarch64
          path: out-aarch64/
      - name: Rename artifacts
        run: |
          for f in out-x86_64/*; do
            mv "$f" "out-x86_64/$(basename $f)-x86_64"
          done
          for f in out-aarch64/*; do
            mv "$f" "out-aarch64/$(basename $f)-aarch64"
          done
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            out-x86_64/**
            out-aarch64/**
